In [4]:
import polars as pl

# Load dataset safely
df = pl.read_csv(
    "../data/data.csv",
    encoding="latin-1",
    ignore_errors=True
)

df.head()

shape: (5, 8)
┌───────────┬───────────┬──────────────┬──────────┬─────────────┬───────────┬────────────┬─────────┐
│ InvoiceNo ┆ StockCode ┆ Description  ┆ Quantity ┆ InvoiceDate ┆ UnitPrice ┆ CustomerID ┆ Country │
│ ---       ┆ ---       ┆ ---          ┆ ---      ┆ ---         ┆ ---       ┆ ---        ┆ ---     │
│ i64       ┆ str       ┆ str          ┆ i64      ┆ str         ┆ f64       ┆ i64        ┆ str     │
╞═══════════╪═══════════╪══════════════╪══════════╪═════════════╪═══════════╪════════════╪═════════╡
│ 536365    ┆ 85123A    ┆ WHITE        ┆ 6        ┆ 12/1/2010   ┆ 2.55      ┆ 17850      ┆ United  │
│           ┆           ┆ HANGING      ┆          ┆ 8:26        ┆           ┆            ┆ Kingdom │
│           ┆           ┆ HEART        ┆          ┆             ┆           ┆            ┆         │
│           ┆           ┆ T-LIGHT HO…  ┆          ┆             ┆           ┆            ┆         │
│ 536365    ┆ 71053     ┆ WHITE METAL  ┆ 6        ┆ 12/1/2010   ┆ 3.39      ┆ 17850      ┆ United  │
│           ┆           ┆ LANTERN      ┆          ┆ 8:26        ┆           ┆            ┆ Kingdom │
│ 536365    ┆ 84406B    ┆ CREAM CUPID  ┆ 8        ┆ 12/1/2010   ┆ 2.75      ┆ 17850      ┆ United  │
│           ┆           ┆ HEARTS COAT  ┆          ┆ 8:26        ┆           ┆            ┆ Kingdom │
│           ┆           ┆ HANGER       ┆          ┆             ┆           ┆            ┆         │
│ 536365    ┆ 84029G    ┆ KNITTED      ┆ 6        ┆ 12/1/2010   ┆ 3.39      ┆ 17850      ┆ United  │
│           ┆           ┆ UNION FLAG   ┆          ┆ 8:26        ┆           ┆            ┆ Kingdom │
│           ┆           ┆ HOT WATER B… ┆          ┆             ┆           ┆            ┆         │
│ 536365    ┆ 84029E    ┆ RED WOOLLY   ┆ 6        ┆ 12/1/2010   ┆ 3.39      ┆ 17850      ┆ United  │
│           ┆           ┆ HOTTIE WHITE ┆          ┆ 8:26        ┆           ┆            ┆ Kingdom │
│           ┆           ┆ HEART.       ┆          ┆             ┆           ┆            ┆         │
└───────────┴───────────┴──────────────┴──────────┴─────────────┴───────────┴────────────┴─────────┘

In [5]:
df = df.with_columns(
    pl.col("InvoiceDate").str.to_datetime("%m/%d/%Y %H:%M")
)

In [6]:
df = df.drop_nulls("CustomerID")

In [7]:
df = df.with_columns(
    (pl.col("Quantity") * pl.col("UnitPrice")).alias("Revenue")
)

In [ ]:
# Get latest date in dataset
snapshot_date = df.select(pl.col("InvoiceDate").max()).to_series()[0]

# Create RFM
rfm = df.group_by("CustomerID").agg([
    (snapshot_date - pl.col("InvoiceDate").max()).dt.total_days().alias("Recency"),
    pl.col("InvoiceNo").n_unique().alias("Frequency"),
    pl.col("Revenue").sum().alias("Monetary")
])

rfm.head()

shape: (5, 4)
┌────────────┬─────────┬───────────┬──────────┐
│ CustomerID ┆ Recency ┆ Frequency ┆ Monetary │
│ ---        ┆ ---     ┆ ---       ┆ ---      │
│ i64        ┆ i64     ┆ u32       ┆ f64      │
╞════════════╪═════════╪═══════════╪══════════╡
│ 17069      ┆ 27      ┆ 10        ┆ 2655.22  │
│ 15235      ┆ 217     ┆ 12        ┆ 2247.51  │
│ 13115      ┆ 8       ┆ 5         ┆ 2205.63  │
│ 14443      ┆ 53      ┆ 5         ┆ 1400.88  │
│ 13520      ┆ 58      ┆ 7         ┆ 3487.75  │
└────────────┴─────────┴───────────┴──────────┘

In [10]:
from scipy.stats import zscore
import pandas as pd

# Convert Polars DataFrame to Pandas
rfm_pd = rfm.to_pandas()

# Remove outliers using Z-score
rfm_pd = rfm_pd[
    (abs(zscore(rfm_pd[['Recency', 'Frequency', 'Monetary']])) < 3).all(axis=1)
]

rfm_pd.head()

   CustomerID  Recency  Frequency  Monetary
0       17069       27         10   2655.22
1       15235      217         12   2247.51
2       13115        8          5   2205.63
3       14443       53          5   1400.88
4       13520       58          7   3487.75

In [11]:
rfm_clean = pl.from_pandas(rfm_pd)

In [12]:
rfm_clean.write_csv("../data/processed_features.csv")